local function main()
  local PointCloudViewer = require("ViewerModule")
  local Triangle = require("Triangle")
  local DataProcessing = require("DataProcessing")
  local Communication = require("Communication")
  local cloud = Triangle.createTwoLines()
  --local cloud = Triangle.createOneLine()
  --local cloud = Triangle.createOneLineWithFirstPointAsClosestPoint()
  local changedCloud = DataProcessing.removePointsBeyond(cloud, 1000)
  local firstPoint, secondPoint, distance = DataProcessing.getTwoCornersAndEdgeLength(changedCloud)
  local firstX, firstY = firstPoint:getXY()
  local secondX, secondY = secondPoint:getXY()
  print(firstX, firstY, secondX, secondY, distance)
  local thirdPoint = DataProcessing.getThirdCorner(Point.create(0,0),Point.create(150, 0), 150)
  local thirdX, thirdY = thirdPoint:getXY()
  print("Dritter Punkt: ", thirdX, thirdY)
  PointCloudViewer.PointCloudViewer(changedCloud)

  --scanProvider = Scan.Provider.Scanner.create()
  --Communication.sendScans(scanProvider, "192.168.1.20")

end
Script.register("Engine.OnStarted", main)